---
trainer:
  class_path: eva.Trainer
  init_args:
    n_runs: &N_RUNS ${oc.env:N_RUNS, 1}
    default_root_dir: ${oc.env:OUTPUT_ROOT, logs/${oc.env:MODEL_NAME, anthropic-claude-3-7-sonnet-latest}/pubmedqa}
    checkpoint_type: null
    accelerator: ${oc.env:ACCELERATOR, auto}
    devices: ${oc.env:NUM_DEVICES, 1}
    callbacks:
      - class_path: eva.callbacks.ConfigurationLogger
model:
  class_path: eva.language.models.LanguageModule
  init_args:
    model:
      class_path: eva.language.models.wrappers.ModelFromRegistry
      init_args:
        model_name: ${oc.env:MODEL_NAME, anthropic/claude-3-7-sonnet-20250219}
        model_extra_kwargs: ${oc.env:MODEL_EXTRA_KWARGS, null}
    metrics:
      common:
        - class_path: eva.metrics.MulticlassClassificationMetrics
          init_args:
            num_classes: 3
            input_type: "discrete"
    postprocess:
      predictions_transforms:
        - class_path: eva.language.models.postprocess.ExtractDiscreteAnswer
          init_args:
            answer_format: ${oc.env:ANSWER_FORMAT, json}
            extract_kwargs:
              mapping: {"no": 0, "yes": 1, "maybe": 2}
              missing_limit: ${oc.env:MISSING_LIMIT, 5}
              missing_answer: ${oc.env:MISSING_ANSWER, 2}
data:
  class_path: eva.DataModule
  init_args:
    datasets:
      val:
        class_path: eva.language.datasets.PubMedQA
        init_args: &DATASET_ARGS
          root: ${oc.env:DATA_ROOT, ./data/pubmedqa}
          split: val
          download: ${oc.env:DOWNLOAD_DATA, false}
          # Set `download: true` to download the dataset from https://huggingface.co/datasets/bigbio/pubmed_qa
          # The PubMedQA dataset is distributed under the following license: MIT License
          # See (https://github.com/pubmedqa/pubmedqa/blob/master/LICENSE)
          prompt_template:
            class_path: eva.language.prompts.templates.MultipleChoicePromptTemplate
            init_args:
              answer_format: ${oc.env:ANSWER_FORMAT, json}
      test:
        class_path: eva.language.datasets.PubMedQA
        init_args:
          <<: *DATASET_ARGS
          split: test
    dataloaders:
      val: &DATALOADER_ARGS
        batch_size: &BATCH_SIZE ${oc.env:BATCH_SIZE, 16}
        num_workers: &N_DATA_WORKERS ${oc.env:N_DATA_WORKERS, 1}
        shuffle: false
        collate_fn: eva.language.data.dataloaders.text_collate
      test:
        <<: *DATALOADER_ARGS
